apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  annotations: {}
  name: monitoring
  namespace: elastic
spec:
  nodeSets:
    - config:
        node.store.allow_mmap: false
      count: 1
      name: default
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: managed-standard
      podTemplate:
        spec:
          containers:
            - env:
                - name: READINESS_PROBE_TIMEOUT
                  value: "10"
              name: elasticsearch
              readinessProbe:
                exec:
                  command:
                    - bash
                    - "-c"
                    - /mnt/elastic-internal/scripts/readiness-probe-script.sh
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 12
                successThreshold: 1
                timeoutSeconds: 12

  version: 8.8.0
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: monitoring
  namespace: elastic
spec:
  #host: elasticsearch.example.com # override if you don't want to use the host that is automatically generated by OpenShift (<route-name>[-<namespace>].<suffix>)
  tls:
    termination: passthrough # Elasticsearch is the TLS endpoint
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: monitoring-es-http