apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  annotations: {}
  name: logstash
  namespace: elastic
spec:
  count: 1
  elasticsearchRefs:
    - clusterName: eck
      name: monitoring
  pipelines:
    - config.string: |
        input {
          beats {
            port => 5044
          }
        }
        filter {
          if [kubernetes][namespace] {
            mutate {
              add_field => {
                "[@metadata][index]" => "%{[kubernetes][namespace]}"
              }
            }
          }
        }
        output {
          elasticsearch {
            hosts => [ "${ECK_ES_HOSTS}" ]
            user => "elastic"
            password => "W0MmLg1t2z55WIKZ9U8o392X"
            cacert => "${ECK_ES_SSL_CERTIFICATE_AUTHORITY}"
            index => "%{[@metadata][index]}"
          }
        }
      pipeline.id: main
  services:
    - name: beats
      service:
        spec:
          ports:
            - name: filebeat
              port: 5044
              protocol: TCP
              targetPort: 5044
          type: ClusterIP
  version: 8.8.0
