apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  annotations: {}
  name: filebeat
  namespace: elastic
spec:
  config:
    # logging.level: debug
    filebeat:
      autodiscover:
        providers:
          - hints:
              default_config:
                paths:
                  - /var/log/containers/*${data.kubernetes.container.id}.log
                type: container
              enabled: true
            node: "${NODE_NAME}"
            type: kubernetes
    processors:
      - add_cloud_metadata: {}
      - add_host_metadata: {}
      # - script:
      #     lang: javascript
      #     id: extract_tenant_name
      #     source: >
      #       function process(event) {
      #         var namespace = event.Get("kubernetes.namespace");
      #         var tenantName = namespace.split('-')[0];
      #         event.Put('tenant_name', tenantName);
      #         return event;
      #       }
    output.kafka:
      hosts:
        - my-cluster-kafka-brokers.kafka.svc.cluster.local:9092
      topic: example-topic
     # topic: "%{[tenant_name]}"
      # topics: 
      #   - topic: "blackops"    
  daemonSet:
    podTemplate:
      spec:
        automountServiceAccountToken: true
        containers:
          - env:
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            name: filebeat
            securityContext:
              privileged: true
              runAsUser: 0
            volumeMounts:
              - mountPath: /var/log/containers
                name: varlogcontainers
              - mountPath: /var/log/pods
                name: varlogpods
              - mountPath: /var/lib/docker/containers
                name: varlibdockercontainers
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        serviceAccountName: filebeat
        terminationGracePeriodSeconds: 30
        volumes:
          - hostPath:
              path: /var/log/containers
            name: varlogcontainers
          - hostPath:
              path: /var/log/pods
            name: varlogpods
          - hostPath:
              path: /var/lib/docker/containers
            name: varlibdockercontainers
  type: filebeat
  version: 8.8.0
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: filebeat
# rules:
# - apiGroups: [""] # "" indicates the core API group
#   resources:
#   - namespaces
#   - pods
#   - nodes
#   verbs:
#   - get
#   - watch
#   - list
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: filebeat
#   namespace: elastic
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: filebeat
# subjects:
# - kind: ServiceAccount
#   name: filebeat
#   namespace: elastic
# roleRef:
#   kind: ClusterRole
#   name: filebeat
#   apiGroup: rbac.authorization.k8s.io