apiVersion: stackconfigpolicy.k8s.elastic.co/v1alpha1
kind: StackConfigPolicy
metadata:
  name: test-stack-config-policy
  namespace: elastic
spec:
  elasticsearch:
    indexTemplate:
      composableIndexTemplates:
        blackops:
          composed_of:
          - logs-settings
          - logs-mappings
          index_patterns:
          - blackops*
          template:
            index:
              lifecycle:
                name: delete-after-one-day
                rollover_alias: elastic
    indexLifecyclePolicies:
      delete-later-1-day:
        phases:
          delete:
            actions:
              delete: {}
            min_age: 1d

