apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: random-logger
          image: expruc/random-logger
          resources: {}
          volumeMounts:
            - name: logs
              mountPath: /tmp
        - name: filebeat-sidecar
          image: docker.elastic.co/beats/filebeat-ubi8:8.8.0
          volumeMounts:
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
            - name: logs
              mountPath: /tmp/
      volumes:
        - name: logs
        - name: filebeat-config
          configMap:
            name: filebeat-sidecar-configmap
            items:
              - key: filebeat.yml
                path: filebeat.yml
---
# Source: vector/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-sidecar-configmap
  namespace: elastic
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths: ["/tmp/*"]
    name: blackops-sidecar
    setup.template.name: "grafana-try"
    setup.template.pattern: "grafana-try*"
    output.elasticsearch:
      hosts: ["https://monitoring-es-http.elastic.svc:9200"]
      index: "grafana-try"
      username: elastic
      password: W0MmLg1t2z55WIKZ9U8o392X    
      ssl.certificate_authorities: |
        -----BEGIN CERTIFICATE-----
        MIIDSjCCAjKgAwIBAgIRALf4QsHdZhFi6VVkEmIUrBYwDQYJKoZIhvcNAQELBQAw
        LzETMBEGA1UECxMKbW9uaXRvcmluZzEYMBYGA1UEAxMPbW9uaXRvcmluZy1odHRw
        MB4XDTIzMDYxODA2NDIwNVoXDTI0MDYxNzA2NTIwNVowLzETMBEGA1UECxMKbW9u
        aXRvcmluZzEYMBYGA1UEAxMPbW9uaXRvcmluZy1odHRwMIIBIjANBgkqhkiG9w0B
        AQEFAAOCAQ8AMIIBCgKCAQEAsYj2plfODSYjiBhLmQckj5uH+XkkxAKlLx2/lJmW
        LyjKON22EwajXsgN9CO6Vm4CWHhUVCPbAshD4KkNAnQO/NyXbBZy5O1WoIJVTcKQ
        JqQ7Pcdf0ByO3xBQZ4uYsEtjZkTmQHYhWyaEeO8r95de2fLPQIwy5sqsvv5ccb9R
        VpsoTeZwogup1T+7KZuQBXZ/At+ynthb77FRswaWly06mtZmyxyl+vNHdHvusrss
        EwEDum6l0qE5b/+T1JtLsZn3uCIut/K+pEhZ1M5wh1fizM6K2t4ZW03rFrWLMJNw
        5xV22iEkBMux+8rTi344zisLlIGpJGaE/NfRC4WJVJh9HQIDAQABo2EwXzAOBgNV
        HQ8BAf8EBAMCAoQwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1Ud
        EwEB/wQFMAMBAf8wHQYDVR0OBBYEFExFneKXrJZaMVPrKRzb0nZqcFdJMA0GCSqG
        SIb3DQEBCwUAA4IBAQBjVBZBa97B/zmR1O9vjDsM5pr+DQtPBcm4xdZUGKZgWvxC
        UJzl3Ng8rlMPhUHPMx/6waalpnmEtIhypK0UIQuqDJ9aOMDhQPdG4WM5PzffixSl
        BBQ0ZKrhTrZ0Q5JhJm/2hixXhN3e5jqQpbGmF4D5Poj6OSuop4kph7W8UaZFC4l7
        i9pHtJXPUPA7dDK5QdHeExdtSWfsIvTV7sqwGBd0AJrF9F76sTJ/+PcAHvB/zpTD
        LrxjRqe34AiG0HYsNhVhNtbLRIqgqx57MRnj5nxiiGWvgsmd+It/RONhbiml3T1Z
        escSpS04tdRnbQNpvxIvWl/eMKSetvlVRUbOoahJ
        -----END CERTIFICATE-----
