apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: connector-elasticsearch-sink
  labels:
    strimzi.io/cluster: my-connect-cluster-elastic-build
spec:
  class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
  config:
    key.ignore: true
    elastic.https.ssl.truststore.type: JKS
    elastic.https.ssl.truststore.password: Aa123456
    topics: example-topic
    connection.username: elastic
    connection.password: Gli69H0RERN8O8544qE3a9To
    elastic.security.protocol: SSL
    elastic.https.ssl.truststore.location: /opt/kafka/external-configuration/certificates/certificate.jks
    connection.url: 'https://monitoring-es-http.elastic.svc:9200'
    schema.ignore: true
    read.timeout.ms: 180000
    # batch.size: 10000
    # max.buffered.records: 200000
    transforms: routeTS
    transforms.routeTS.type: org.apache.kafka.connect.transforms.TimestampRouter
    transforms.routeTS.topic.format: "${topic}-${timestamp}"
    transforms.routeTS.timestamp.format: "yyyy-MM-dd"
    flush.synchronously: "true"
    # data.stream.dataset: .ds_logs_example
    # data.stream.type: logs
  tasksMax: 5
