apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: connector-elasticsearch-sink
  labels:
    strimzi.io/cluster: my-connect-cluster-elastic-build
spec:
  class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
  config:
    key.ignore: true
    elastic.https.ssl.truststore.type: JKS
    elastic.https.ssl.truststore.password: Aa123456
    topics: example-topic
    connection.username: elastic
    connection.password: Gli69H0RERN8O8544qE3a9To
    elastic.security.protocol: SSL
    elastic.https.ssl.truststore.location: /opt/kafka/external-configuration/certificates/certificate.jks
    connection.url: 'https://monitoring-es-http.elastic.svc:9200'
    schema.ignore: true
  tasksMax: 1
